// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqsoinctwpcerpdmltmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxc29pbmN0d3BjZXJwZG1sdG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyOTQyOTYsImV4cCI6MjA2Mzg3MDI5Nn0.tOHKW79PKr1BqUntEfmG9nSu7s2lEYyBMJ_CuVZmer4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);